### status
GET http://localhost:5000/status


### Boas vindas
GET http://localhost:5000/contas/1313-0
Authorization: Bearer 53125ab14940f1d4689ba6356e3df75143248fe2e0d8ba6b0907c0bb12ec9424fee0dcc954b8ae9c81f03236780cdb5a4cdcabb02494e1dca83d4ab8bf4af711

### Saldo
GET http://localhost:5000/contas/1313-0/saldo
Authorization: Bearer 53125ab14940f1d4689ba6356e3df75143248fe2e0d8ba6b0907c0bb12ec9424fee0dcc954b8ae9c81f03236780cdb5a4cdcabb02494e1dca83d4ab8bf4af711

### Depósito DINHEIRO
POST http://localhost:5000/contas/1313-0/deposito
Content-Type: application/json

{
  "valor": 100,
  "tipo_deposito": "DINHEIRO"
}

### Login
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "fulano@email.com",
  "senha": "123456"
}

### Login pessoa
POST http://localhost:5000/pessoas/login
Content-Type: application/json

{
  "usuario": "Davi",
  "senha": "123456"
}

### Cadastro pessoa
POST http://localhost:5000/pessoas/cadastrar
Content-Type: application/json

{
  "nome_completo": "Davi do Carmo",
  "cpf": "123456789",
  "usuario": "Davi",
  "senha": "123456"
}
### Atualizar dados pessoa
POST http://localhost:5000/pessoas/b674a97a-3b6b-4f8e-bb66-d4a21611bfc6/atualizar
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwZXNzb2FfaWQiOiJiNjc0YTk3YS0zYjZiLTRmOGUtYmI2Ni1kNGEyMTYxMWJmYzYiLCJwcml2aWxlZ2lvIjoic2VtLWFjZXNzbyIsImlhdCI6MTcwNzM1Mzg3NiwiZXhwIjoxNzA3MzU3NDc2fQ.wqjpFh0CrYvvKavJd8XRRg3Is8iRR3jFWpUjMCfA_6c

{
  "nome_completo": "Davi Bertan",
  "cpf": "12345674343",
  "usuario": "Davi",
  "senha": "123456"
}