### status

GET http://localhost:5000/status

### boas vindas

GET http://localhost:5000/contas/1313-0

### saldo

GET http://localhost:5000/contas/1313-0/saldo


###deposito DINHEIRO
POST  http://localhost:5000/contas/1313-0/deposito
Content-Type: application/json

{
    "valor": 100,   
    "tipo": "DINHEIRO"
}



###LOGIN
POST  http://localhost:5000/login
Content-Type: application/json

{
    "email": "fulano@gmail.com",   
    "senha": "123456"
}